### ISSUE TITLE
Window size

### ISSUE THREAD

**Issue by yuuretsu** [not-fl3/macroquad#23]
Сan i set the window size? and can i forbid changing it?

**Comment by zotho** [comment]
@yuuretsu Currently no. Window creation begins in [macro](https://github.com/not-fl3/macroquad/blob/master/macroquad_macro/src/lib.rs#L40). And continues in method [`new`](https://github.com/not-fl3/macroquad/blob/master/src/lib.rs#L309). You can change this method and add a [required field](https://docs.rs/miniquad/0.2.55/miniquad/conf/struct.Conf.html#structfield.window_width) in `conf::Conf`.

Forbidding for change size is more deep in `miniquad` package.

**Comment by chrisburnor** [comment]
Could you simply add a `miniquad::Conf` param to `macroquad::Window::new()` and that be the 'custom' way of starting a macroquad app, while leaving the macro as the 'default' case?

**Comment by zotho** [comment]
I think this issue is resolved by PR https://github.com/not-fl3/macroquad/pull/32. See [`window_conf.rs`](https://github.com/not-fl3/macroquad/blob/master/examples/window_conf.rs) example - you can also pass [`window_width` and `window_height`](https://docs.rs/miniquad/0.2.55/miniquad/conf/struct.Conf.html#structfield.window_width) parameters instead of `fullscreen`

**Comment by not-fl3** [comment]
Your right @zotho

Closing this.
