### ISSUE TITLE
wasm failed to load. Incompatable gl.js version

### ISSUE THREAD

**Issue by ZacharyGillmore** [not-fl3/macroquad#542]
![Screenshot from 2022-12-22 01-09-49](https://user-images.githubusercontent.com/88333868/209099063-e8bab653-901b-411c-a933-58f0532dc3c8.png)

```html
<body>
    <canvas id="glcanvas" tabindex='1'></canvas>
    <!-- Minified and statically hosted version of https://github.com/not-fl3/macroquad/blob/master/js/mq_js_bundle.js -->
    <script src="https://not-fl3.github.io/miniquad-samples/mq_js_bundle.js"></script>
    <script>load("snake.wasm");</script> <!-- Your compiled wasm file -->
</body>
```
macroquad  version "0.3.25"

**Comment by FaunKr** [comment]
This seems more like not using a webserver at all and instead directly accessing the file from the local file system. You can tell that because the url in the error starts with `file://`  instead of `http://` or `https://`.

Most browser forbid running wasm directly from the local file system (e.g.  you opening the index.html via "open with firefox/chrome). 

But using `basic-http-server` should solve that too.

**Comment by ZacharyGillmore** [comment]
Sorry looks like this error was my fault. Wasn't using a server. Though if I need a webserver how would I go about uploading it to itch.io for example? Or is that not an option

**Comment by not-fl3** [comment]
> Sorry looks like this error was my fault. Wasn't using a server. Though if I need a webserver how would I go about uploading it to itch.io for example? Or is that not an option

itch.io puts all the correct mime types on .wasm files

in other words, uploading to itch.io works just fine
