### ISSUE TITLE
set_cursor_grab and show_mouse don't work on Windows

### ISSUE THREAD

**Issue by MyUsernamee** [not-fl3/macroquad#549]
It appears as though set_cursor_grab and show_mouse do not work on windows, though it does work in wasm.
I tested this with both msvc and gnu toolchains.
I am running Windows 10.
This was tested across two different computers with [Mee](https://github.com/Mee12345)

# Steps to reproduce
1. Create a new cargo project.
2. cargo add macroquad
3. Add this code to the main 
```rust
use macroquad::prelude::*;

#[macroquad::main("HelloWorld")]
async fn main() {
    set_cursor_grab(true);
    show_mouse(false);
    loop {
        clear_background(BLACK);
        draw_text("Hello, world!", 20.0, 20.0, 20.0, WHITE);
        next_frame().await
    }
}
```
4. cargo run
5. The mouse shouldn't lock or hide.

If there is any more information or testing that is needed please let me know. :)

**Comment by unc0mm0n** [comment]
Hi @not-fl3, So I looked into this today when I noticed that the first person example doesn't grab the mouse on windows.

The issue is that miniquad 0.3.14 didn't implement these functions (they are empty stubs). 0.3.15 does implement them but you can't just bump macroquad to 0.3.15 as that version changed `src/graphics/textures.rs` (in miniquad) and now the `texture.format.into()` in `src/textures.rc:681` (in macroquad) doesn't compile.

Now in order to replace it with the new `texture.format.into_gl_params` you also need to modify miniquad to make that function public, which means you need a new release for miniquad (or to find a different way of getting an internal_format in the macroquad line above)

**Comment by MyUsernamee** [comment]
It seems as though this issue was fixed with newer update of macroquad so I am going to close this issue :)
