### ISSUE TITLE
Command-Q does not quit program on macOS

### ISSUE THREAD

**Issue by alterae** [not-fl3/macroquad#649]
On macOS, the customary shortcut to quit any application is Command-Q (LeftSuper-Q using macroquad KeyCodes). However, this does not work in macroquad applications.

While it is trivial to implement by hand, it is still a bit annoying and mac users generally expect Command-Q to work on all platforms.

If this could be implemented in the engine, that would be excellent.

**Comment by markmurphydev** [comment]
I've submitted not-fl3/miniquad#464 to add a menu bar entry with a "quit application" shortcut. This is the normal way to implement the command-q shortcut on osx, and lets you rebind it in system keyboard settings.

Note that on osx on master, clicking on a menu bar item currently freezes the window. This is due to not-fl3/miniquad#455.

The Winit crate also adds by default the "About application", "Services", "Hide application", "Hide others", and "Show all" menu items. These are also standard Mac menu items, with system-default implementations. I can add them if we want.
